import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "./component/Head";
import SecondHeader from "./component/SecondHeader";
import Footer from "./component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UzRoboUp",
  description: "Generated by Priyansh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
      <Footer />
    </html>
  );
}
